---
- name: Install OpenSSH server and client
  when: enable_ssh and ansible.os_installation_type == "Server"
  ansible.windows.win_feature:
    state: present
    name: "{{ capability }}"
  loop:
  - OpenSSH.Client~~~~0.0.1.0
  - OpenSSH.Server~~~~0.0.1.0
  loop_control:
    loop_var: capability
  become: true

- name: Ensure firewall rule for OpenSSH service exists
  when: enable_ssh and ansible.os_installation_type == "Server"
  community.windows.win_firewall_rule:
    name: OpenSSH Server (sshd)
    localport: 22
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  become: true

- name: Add insecure vagrant ssh key to authorized_keys
  when: enable_ssh and add_vagrant_ssh_pubkey and ansible.os_installation_type == "Server"
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('url', 'https://raw.github.com/hashicorp/vagrant/master/keys/vagrant.pub', split_lines=False) }}"
  become: true

- name: Start and enable OpenSSH service
  when: enable_ssh and ansible.os_installation_type == "Server"
  ansible.windows.win_service:
    name: sshd
    state: running
    start_mode: auto
  become: true
