---
- name: Suppress prompt for network location
  when: set_all_networks_private
  ansible.windows.win_regedit:
    path: HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Network\\NewNetworkWindowOff
    state: present
  become: true

- name: Set all network connections to Private
  when: set_all_networks_private
  ansible.windows.win_shell: >
    Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory "Private"
  become: true
